export const HIDE_LOADING = 'HIDE_LOADING';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
export const SHOW_LOADING = 'SHOW_LOADING';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const TOGGLE_LOADING = 'TOGGLE_LOADING';
export const TOGGLE_NOTIFICATION = 'TOGGLE_NOTIFICATION';

export const USERS_LIST_FETCH = 'USERS_LIST_FETCH';
export const USERS_LIST_FETCH_SUCCESS = 'USERS_LIST_FETCHED';
export const USERS_LIST_FETCH_ERROR = 'USERS_LIST_FETCH_ERROR';

export const  USER_GET = 'USER_GET';
export const USER_GET_SUCCESS = 'USER_GET_SUCCESS';
export const USER_GET_ERROR = 'USER_GET_ERROR';